# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='must_see_place',
            field=wagtail.wagtailcore.fields.StreamField([('must_see_place', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('place', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('background', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('first_recomendation', wagtail.wagtailcore.blocks.PageChooserBlock()), ('second_recomendation', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, null=True, required=False))], icon='pick'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
