# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170130_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='must_see_place',
            field=wagtail.wagtailcore.fields.StreamField([('body', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True))], icon='pick'))], blank=True, null=True),
        ),
    ]
