# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:57
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170130_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='must_see_place',
            new_name='body_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.wagtailcore.fields.StreamField([('body', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True))], icon='pick'))], blank=True, null=True),
        ),
    ]
