# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170130_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='french_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='spanish_link',
        ),
    ]
